<?php

namespace Botble\Bycode\Repositories\Eloquent;

use Botble\Bycode\Models\Bycode;
use Botble\Support\Repositories\Eloquent\RepositoriesAbstract;
use Botble\Bycode\Repositories\Interfaces\BycodeInterface;

class BycodeRepository extends RepositoriesAbstract implements BycodeInterface
{
    public function setModel($model)
    {
        return Bycode::class; // TODO: Change the autogenerated stub
    }
}
